name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

env:
  DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker images
      run: |
        docker-compose build

    - name: Deploy to DigitalOcean
      uses: sodx/tickets@v1
      with:
        access-token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        context: production
        env-file: production.env
