name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

env:
  DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
  DROPLET_ID: ${{ secrets.DROPLET_ID }}
  DO_API_KEY: ${{ secrets.DO_API_KEY }}
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
  name: Deploy
      
  # Authenticate to the the server via ssh 
  # and run our deployment script 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: "cd /var/www/liveconcerts && ./scripts/deploy.sh"
      - uses: actions/checkout@v2
      - name: Deploy to server 2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_WSIEVENTS }}
          username: ${{ secrets.USERNAME_WSIEVENTS }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY_WSIEVENTS }}
          script: "cd /var/www/laravel && ./scripts/deploy.sh"
# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout repository
#       uses: actions/checkout@v2

#     - name: Configure SSH
#       uses: ssh-actions/ssh-add-key@v2
#       with:
#         ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
#         ssh-known-hosts: digitalocean.com

#     - name: Deploy Laravel Sail
#       uses: docker/deploy-action@v2
#       with:
#         context: .
#         push: true          
#
